package com.firefly

import com.firefly.drools.test.User;

rule "roo1"
    salience 3
    when
        $u:User(money>0);
    then
        System.out.println("余钱："+$u.getMoney()+",花1元购买1瓶并喝掉");
        $u.setKp($u.getKp()+1);
        $u.setMoney($u.getMoney()-1);
        $u.setTotals($u.getTotals()+1);
        update($u);
end

rule "roo2"
    salience 2
    when
        $u:User(kp>=2);
    then
        System.out.println("空瓶数："+$u.getKp()+",兑换2个空瓶为1元钱！");
        $u.setKp($u.getKp()-2);
        $u.setMoney($u.getMoney()+1);
        update($u);
end

rule "roo3"
    salience 3
    when
        $u:User();
    then
        System.out.println("总喝掉瓶数：" + $u.getTotals());
end
